CREATE TABLE IF NOT EXISTS USERS (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(20),
    SURNAME VARCHAR(25),
    EMAIL VARCHAR(30),
    PASSWORD VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS PROJECTS (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(20),
    DESCRIPTION VARCHAR(200),
    START DATE,
    FINISH DATE,
    FOREIGN KEY (TASKS_ID) REFERENCES TASKS(ID)


);

CREATE TABLE IF NOT EXISTS TASKS (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(20),
    DESCRIPTION VARCHAR(200),
    DEADLINE DATE,
    STATUS ENUM ('DONE', 'IN_PROGRESS'),
    COMPLETED BOOL,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)


);








